// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: writing_process_info.proto

#include "writing_process_info.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace phoenix {
namespace msg {
namespace localization {
class WritingProcessInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WritingProcessInfo>
      _instance;
} _WritingProcessInfo_default_instance_;
class WritingParamsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WritingParams>
      _instance;
} _WritingParams_default_instance_;
class WritingSysDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WritingSys>
      _instance;
} _WritingSys_default_instance_;
}  // namespace localization
}  // namespace msg
}  // namespace phoenix
namespace protobuf_writing_5fprocess_5finfo_2eproto {
void InitDefaultsWritingProcessInfoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingSys();
  protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingParams();
  {
    void* ptr = &::phoenix::msg::localization::_WritingProcessInfo_default_instance_;
    new (ptr) ::phoenix::msg::localization::WritingProcessInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::phoenix::msg::localization::WritingProcessInfo::InitAsDefaultInstance();
}

void InitDefaultsWritingProcessInfo() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsWritingProcessInfoImpl);
}

void InitDefaultsWritingParamsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::phoenix::msg::localization::_WritingParams_default_instance_;
    new (ptr) ::phoenix::msg::localization::WritingParams();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::phoenix::msg::localization::WritingParams::InitAsDefaultInstance();
}

void InitDefaultsWritingParams() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsWritingParamsImpl);
}

void InitDefaultsWritingSysImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::phoenix::msg::localization::_WritingSys_default_instance_;
    new (ptr) ::phoenix::msg::localization::WritingSys();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::phoenix::msg::localization::WritingSys::InitAsDefaultInstance();
}

void InitDefaultsWritingSys() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsWritingSysImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, sitecode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, sys_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, params_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingProcessInfo, method_),
  6,
  0,
  1,
  2,
  4,
  5,
  3,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, offset_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, offset_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, dusting_switch_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, is_move_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingParams, add_material_status_),
  0,
  1,
  2,
  3,
  4,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingSys, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingSys, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::phoenix::msg::localization::WritingSys, ack_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, sizeof(::phoenix::msg::localization::WritingProcessInfo)},
  { 19, 29, sizeof(::phoenix::msg::localization::WritingParams)},
  { 34, 40, sizeof(::phoenix::msg::localization::WritingSys)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::phoenix::msg::localization::_WritingProcessInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::phoenix::msg::localization::_WritingParams_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::phoenix::msg::localization::_WritingSys_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "writing_process_info.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032writing_process_info.proto\022\030phoenix.ms"
      "g.localization\"\315\001\n\022WritingProcessInfo\022\014\n"
      "\004time\030\001 \002(\003\022\n\n\002id\030\002 \001(\t\022\017\n\007version\030\003 \001(\t"
      "\022\020\n\010siteCode\030\004 \001(\t\0221\n\003sys\030\005 \001(\0132$.phoeni"
      "x.msg.localization.WritingSys\0227\n\006params\030"
      "\006 \001(\0132\'.phoenix.msg.localization.Writing"
      "Params\022\016\n\006method\030\007 \001(\t\"\215\001\n\rWritingParams"
      "\022\023\n\010offset_x\030\001 \001(\001:\0010\022\023\n\010offset_y\030\002 \001(\001:"
      "\0010\022\036\n\023dusting_switch_type\030\003 \001(\005:\0010\022\022\n\007is"
      "_move\030\004 \001(\005:\0010\022\036\n\023add_material_status\030\005 "
      "\001(\005:\0010\"\034\n\nWritingSys\022\016\n\003ack\030\001 \001(\005:\0010"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 436);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "writing_process_info.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_writing_5fprocess_5finfo_2eproto
namespace phoenix {
namespace msg {
namespace localization {

// ===================================================================

void WritingProcessInfo::InitAsDefaultInstance() {
  ::phoenix::msg::localization::_WritingProcessInfo_default_instance_._instance.get_mutable()->sys_ = const_cast< ::phoenix::msg::localization::WritingSys*>(
      ::phoenix::msg::localization::WritingSys::internal_default_instance());
  ::phoenix::msg::localization::_WritingProcessInfo_default_instance_._instance.get_mutable()->params_ = const_cast< ::phoenix::msg::localization::WritingParams*>(
      ::phoenix::msg::localization::WritingParams::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WritingProcessInfo::kTimeFieldNumber;
const int WritingProcessInfo::kIdFieldNumber;
const int WritingProcessInfo::kVersionFieldNumber;
const int WritingProcessInfo::kSiteCodeFieldNumber;
const int WritingProcessInfo::kSysFieldNumber;
const int WritingProcessInfo::kParamsFieldNumber;
const int WritingProcessInfo::kMethodFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WritingProcessInfo::WritingProcessInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingProcessInfo();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:phoenix.msg.localization.WritingProcessInfo)
}
WritingProcessInfo::WritingProcessInfo(const WritingProcessInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_id()) {
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_version()) {
    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  sitecode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_sitecode()) {
    sitecode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sitecode_);
  }
  method_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_method()) {
    method_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.method_);
  }
  if (from.has_sys()) {
    sys_ = new ::phoenix::msg::localization::WritingSys(*from.sys_);
  } else {
    sys_ = NULL;
  }
  if (from.has_params()) {
    params_ = new ::phoenix::msg::localization::WritingParams(*from.params_);
  } else {
    params_ = NULL;
  }
  time_ = from.time_;
  // @@protoc_insertion_point(copy_constructor:phoenix.msg.localization.WritingProcessInfo)
}

void WritingProcessInfo::SharedCtor() {
  _cached_size_ = 0;
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sitecode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  method_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sys_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&time_) -
      reinterpret_cast<char*>(&sys_)) + sizeof(time_));
}

WritingProcessInfo::~WritingProcessInfo() {
  // @@protoc_insertion_point(destructor:phoenix.msg.localization.WritingProcessInfo)
  SharedDtor();
}

void WritingProcessInfo::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sitecode_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  method_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete sys_;
  if (this != internal_default_instance()) delete params_;
}

void WritingProcessInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WritingProcessInfo::descriptor() {
  ::protobuf_writing_5fprocess_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_writing_5fprocess_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WritingProcessInfo& WritingProcessInfo::default_instance() {
  ::protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingProcessInfo();
  return *internal_default_instance();
}

WritingProcessInfo* WritingProcessInfo::New(::google::protobuf::Arena* arena) const {
  WritingProcessInfo* n = new WritingProcessInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WritingProcessInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:phoenix.msg.localization.WritingProcessInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!id_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*id_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!version_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*version_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(!sitecode_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*sitecode_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(!method_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*method_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(sys_ != NULL);
      sys_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(params_ != NULL);
      params_->Clear();
    }
  }
  time_ = GOOGLE_LONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool WritingProcessInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:phoenix.msg.localization.WritingProcessInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->id().data(), static_cast<int>(this->id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "phoenix.msg.localization.WritingProcessInfo.id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string version = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->version().data(), static_cast<int>(this->version().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "phoenix.msg.localization.WritingProcessInfo.version");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string siteCode = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sitecode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sitecode().data(), static_cast<int>(this->sitecode().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "phoenix.msg.localization.WritingProcessInfo.siteCode");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .phoenix.msg.localization.WritingSys sys = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_sys()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .phoenix.msg.localization.WritingParams params = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_params()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string method = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_method()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->method().data(), static_cast<int>(this->method().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "phoenix.msg.localization.WritingProcessInfo.method");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:phoenix.msg.localization.WritingProcessInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:phoenix.msg.localization.WritingProcessInfo)
  return false;
#undef DO_
}

void WritingProcessInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:phoenix.msg.localization.WritingProcessInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int64 time = 1;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->time(), output);
  }

  // optional string id = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->id(), output);
  }

  // optional string version = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->version(), output);
  }

  // optional string siteCode = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sitecode().data(), static_cast<int>(this->sitecode().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.siteCode");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->sitecode(), output);
  }

  // optional .phoenix.msg.localization.WritingSys sys = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->sys_, output);
  }

  // optional .phoenix.msg.localization.WritingParams params = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->params_, output);
  }

  // optional string method = 7;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->method().data(), static_cast<int>(this->method().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.method");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->method(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:phoenix.msg.localization.WritingProcessInfo)
}

::google::protobuf::uint8* WritingProcessInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:phoenix.msg.localization.WritingProcessInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int64 time = 1;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->time(), target);
  }

  // optional string id = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->id(), target);
  }

  // optional string version = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->version(), target);
  }

  // optional string siteCode = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sitecode().data(), static_cast<int>(this->sitecode().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.siteCode");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->sitecode(), target);
  }

  // optional .phoenix.msg.localization.WritingSys sys = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, *this->sys_, deterministic, target);
  }

  // optional .phoenix.msg.localization.WritingParams params = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, *this->params_, deterministic, target);
  }

  // optional string method = 7;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->method().data(), static_cast<int>(this->method().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "phoenix.msg.localization.WritingProcessInfo.method");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->method(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:phoenix.msg.localization.WritingProcessInfo)
  return target;
}

size_t WritingProcessInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:phoenix.msg.localization.WritingProcessInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int64 time = 1;
  if (has_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->time());
  }
  if (_has_bits_[0 / 32] & 63u) {
    // optional string id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->id());
    }

    // optional string version = 3;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->version());
    }

    // optional string siteCode = 4;
    if (has_sitecode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sitecode());
    }

    // optional string method = 7;
    if (has_method()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->method());
    }

    // optional .phoenix.msg.localization.WritingSys sys = 5;
    if (has_sys()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *this->sys_);
    }

    // optional .phoenix.msg.localization.WritingParams params = 6;
    if (has_params()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *this->params_);
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WritingProcessInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:phoenix.msg.localization.WritingProcessInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const WritingProcessInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WritingProcessInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:phoenix.msg.localization.WritingProcessInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:phoenix.msg.localization.WritingProcessInfo)
    MergeFrom(*source);
  }
}

void WritingProcessInfo::MergeFrom(const WritingProcessInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:phoenix.msg.localization.WritingProcessInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_id();
      id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_version();
      version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_sitecode();
      sitecode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sitecode_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_method();
      method_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.method_);
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_sys()->::phoenix::msg::localization::WritingSys::MergeFrom(from.sys());
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_params()->::phoenix::msg::localization::WritingParams::MergeFrom(from.params());
    }
    if (cached_has_bits & 0x00000040u) {
      time_ = from.time_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void WritingProcessInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:phoenix.msg.localization.WritingProcessInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WritingProcessInfo::CopyFrom(const WritingProcessInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:phoenix.msg.localization.WritingProcessInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WritingProcessInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000040) != 0x00000040) return false;
  return true;
}

void WritingProcessInfo::Swap(WritingProcessInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WritingProcessInfo::InternalSwap(WritingProcessInfo* other) {
  using std::swap;
  id_.Swap(&other->id_);
  version_.Swap(&other->version_);
  sitecode_.Swap(&other->sitecode_);
  method_.Swap(&other->method_);
  swap(sys_, other->sys_);
  swap(params_, other->params_);
  swap(time_, other->time_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WritingProcessInfo::GetMetadata() const {
  protobuf_writing_5fprocess_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_writing_5fprocess_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void WritingParams::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WritingParams::kOffsetXFieldNumber;
const int WritingParams::kOffsetYFieldNumber;
const int WritingParams::kDustingSwitchTypeFieldNumber;
const int WritingParams::kIsMoveFieldNumber;
const int WritingParams::kAddMaterialStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WritingParams::WritingParams()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingParams();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:phoenix.msg.localization.WritingParams)
}
WritingParams::WritingParams(const WritingParams& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&offset_x_, &from.offset_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&add_material_status_) -
    reinterpret_cast<char*>(&offset_x_)) + sizeof(add_material_status_));
  // @@protoc_insertion_point(copy_constructor:phoenix.msg.localization.WritingParams)
}

void WritingParams::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&offset_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&add_material_status_) -
      reinterpret_cast<char*>(&offset_x_)) + sizeof(add_material_status_));
}

WritingParams::~WritingParams() {
  // @@protoc_insertion_point(destructor:phoenix.msg.localization.WritingParams)
  SharedDtor();
}

void WritingParams::SharedDtor() {
}

void WritingParams::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WritingParams::descriptor() {
  ::protobuf_writing_5fprocess_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_writing_5fprocess_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WritingParams& WritingParams::default_instance() {
  ::protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingParams();
  return *internal_default_instance();
}

WritingParams* WritingParams::New(::google::protobuf::Arena* arena) const {
  WritingParams* n = new WritingParams;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WritingParams::Clear() {
// @@protoc_insertion_point(message_clear_start:phoenix.msg.localization.WritingParams)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 31u) {
    ::memset(&offset_x_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&add_material_status_) -
        reinterpret_cast<char*>(&offset_x_)) + sizeof(add_material_status_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool WritingParams::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:phoenix.msg.localization.WritingParams)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double offset_x = 1 [default = 0];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_offset_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &offset_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double offset_y = 2 [default = 0];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_offset_y();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &offset_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 dusting_switch_type = 3 [default = 0];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_dusting_switch_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dusting_switch_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 is_move = 4 [default = 0];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_is_move();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &is_move_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 add_material_status = 5 [default = 0];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_add_material_status();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &add_material_status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:phoenix.msg.localization.WritingParams)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:phoenix.msg.localization.WritingParams)
  return false;
#undef DO_
}

void WritingParams::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:phoenix.msg.localization.WritingParams)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double offset_x = 1 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->offset_x(), output);
  }

  // optional double offset_y = 2 [default = 0];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->offset_y(), output);
  }

  // optional int32 dusting_switch_type = 3 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->dusting_switch_type(), output);
  }

  // optional int32 is_move = 4 [default = 0];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->is_move(), output);
  }

  // optional int32 add_material_status = 5 [default = 0];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->add_material_status(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:phoenix.msg.localization.WritingParams)
}

::google::protobuf::uint8* WritingParams::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:phoenix.msg.localization.WritingParams)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double offset_x = 1 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->offset_x(), target);
  }

  // optional double offset_y = 2 [default = 0];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->offset_y(), target);
  }

  // optional int32 dusting_switch_type = 3 [default = 0];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->dusting_switch_type(), target);
  }

  // optional int32 is_move = 4 [default = 0];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->is_move(), target);
  }

  // optional int32 add_material_status = 5 [default = 0];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->add_material_status(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:phoenix.msg.localization.WritingParams)
  return target;
}

size_t WritingParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:phoenix.msg.localization.WritingParams)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 31u) {
    // optional double offset_x = 1 [default = 0];
    if (has_offset_x()) {
      total_size += 1 + 8;
    }

    // optional double offset_y = 2 [default = 0];
    if (has_offset_y()) {
      total_size += 1 + 8;
    }

    // optional int32 dusting_switch_type = 3 [default = 0];
    if (has_dusting_switch_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->dusting_switch_type());
    }

    // optional int32 is_move = 4 [default = 0];
    if (has_is_move()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->is_move());
    }

    // optional int32 add_material_status = 5 [default = 0];
    if (has_add_material_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->add_material_status());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WritingParams::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:phoenix.msg.localization.WritingParams)
  GOOGLE_DCHECK_NE(&from, this);
  const WritingParams* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WritingParams>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:phoenix.msg.localization.WritingParams)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:phoenix.msg.localization.WritingParams)
    MergeFrom(*source);
  }
}

void WritingParams::MergeFrom(const WritingParams& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:phoenix.msg.localization.WritingParams)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      offset_x_ = from.offset_x_;
    }
    if (cached_has_bits & 0x00000002u) {
      offset_y_ = from.offset_y_;
    }
    if (cached_has_bits & 0x00000004u) {
      dusting_switch_type_ = from.dusting_switch_type_;
    }
    if (cached_has_bits & 0x00000008u) {
      is_move_ = from.is_move_;
    }
    if (cached_has_bits & 0x00000010u) {
      add_material_status_ = from.add_material_status_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void WritingParams::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:phoenix.msg.localization.WritingParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WritingParams::CopyFrom(const WritingParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:phoenix.msg.localization.WritingParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WritingParams::IsInitialized() const {
  return true;
}

void WritingParams::Swap(WritingParams* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WritingParams::InternalSwap(WritingParams* other) {
  using std::swap;
  swap(offset_x_, other->offset_x_);
  swap(offset_y_, other->offset_y_);
  swap(dusting_switch_type_, other->dusting_switch_type_);
  swap(is_move_, other->is_move_);
  swap(add_material_status_, other->add_material_status_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WritingParams::GetMetadata() const {
  protobuf_writing_5fprocess_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_writing_5fprocess_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void WritingSys::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WritingSys::kAckFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WritingSys::WritingSys()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingSys();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:phoenix.msg.localization.WritingSys)
}
WritingSys::WritingSys(const WritingSys& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ack_ = from.ack_;
  // @@protoc_insertion_point(copy_constructor:phoenix.msg.localization.WritingSys)
}

void WritingSys::SharedCtor() {
  _cached_size_ = 0;
  ack_ = 0;
}

WritingSys::~WritingSys() {
  // @@protoc_insertion_point(destructor:phoenix.msg.localization.WritingSys)
  SharedDtor();
}

void WritingSys::SharedDtor() {
}

void WritingSys::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WritingSys::descriptor() {
  ::protobuf_writing_5fprocess_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_writing_5fprocess_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WritingSys& WritingSys::default_instance() {
  ::protobuf_writing_5fprocess_5finfo_2eproto::InitDefaultsWritingSys();
  return *internal_default_instance();
}

WritingSys* WritingSys::New(::google::protobuf::Arena* arena) const {
  WritingSys* n = new WritingSys;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WritingSys::Clear() {
// @@protoc_insertion_point(message_clear_start:phoenix.msg.localization.WritingSys)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ack_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool WritingSys::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:phoenix.msg.localization.WritingSys)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 ack = 1 [default = 0];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_ack();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ack_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:phoenix.msg.localization.WritingSys)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:phoenix.msg.localization.WritingSys)
  return false;
#undef DO_
}

void WritingSys::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:phoenix.msg.localization.WritingSys)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 ack = 1 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ack(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:phoenix.msg.localization.WritingSys)
}

::google::protobuf::uint8* WritingSys::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:phoenix.msg.localization.WritingSys)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 ack = 1 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ack(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:phoenix.msg.localization.WritingSys)
  return target;
}

size_t WritingSys::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:phoenix.msg.localization.WritingSys)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional int32 ack = 1 [default = 0];
  if (has_ack()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ack());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WritingSys::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:phoenix.msg.localization.WritingSys)
  GOOGLE_DCHECK_NE(&from, this);
  const WritingSys* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WritingSys>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:phoenix.msg.localization.WritingSys)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:phoenix.msg.localization.WritingSys)
    MergeFrom(*source);
  }
}

void WritingSys::MergeFrom(const WritingSys& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:phoenix.msg.localization.WritingSys)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_ack()) {
    set_ack(from.ack());
  }
}

void WritingSys::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:phoenix.msg.localization.WritingSys)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WritingSys::CopyFrom(const WritingSys& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:phoenix.msg.localization.WritingSys)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WritingSys::IsInitialized() const {
  return true;
}

void WritingSys::Swap(WritingSys* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WritingSys::InternalSwap(WritingSys* other) {
  using std::swap;
  swap(ack_, other->ack_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WritingSys::GetMetadata() const {
  protobuf_writing_5fprocess_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_writing_5fprocess_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace localization
}  // namespace msg
}  // namespace phoenix

// @@protoc_insertion_point(global_scope)
